{% set name = "krakenex" %}
{% set version = "2.0.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "da7911b8bde641ff8fd7db1aeca1f48cc25a717ce48ca3c5ab9fd0247f3eda75" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: 'python setup.py install '

requirements:
  build:
    - python
    - requests >=2.18.2,<3
  run:
    - python
    - requests >=2.18.2,<3

test:
  imports:
    - krakenex

about:
  home: https://github.com/veox/python3-krakenex
  license: ''
  license_family: AGPL
  license_file: ''
  summary: kraken.com cryptocurrency exchange API
  description: ".. image:: https://travis-ci.org/veox/python3-krakenex.svg?branch=master\n   :alt: Latest Travis continuous integration build\n   :target: https://travis-ci.org/veox/python3-krakenex\n..\
    \ image:: https://badges.gitter.im/python3-krakenex/Lobby.svg\n   :alt: Join the chat at https://gitter.im/python3-krakenex/Lobby\n   :target: https://gitter.im/python3-krakenex/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge\n\
    \n\n`krakenex`\n==========\n\nKraken.com exchange API, Python 3 package.\n\nThis package is intentionally as lean as possible, and only\nprovides a minimal interface to the `Kraken`_ cryptocurrency\n\
    exchange.\n\nIntended for developers, not traders.\n\n.. _Kraken: https://kraken.com/\n\n\nDocumentation\n-------------\n\nView the latest_ or stable_ online at ReadTheDocs.\n\nThe code is documented\
    \ in docstrings, and can be viewed with a text editor.\n\nYou can also generate your own with, e.g., ``make html`` in ``doc``.\nThis requires ``sphinx`` and its ``rtd`` theme.\n\nFor the most up-to-date\
    \ list of public/private Kraken API methods, see\ntheir `API documentation`_.\n\n.. _latest: https://python3-krakenex.readthedocs.io/en/latest/\n.. _stable: https://python3-krakenex.readthedocs.io/en/stable/\n\
    .. _API documentation: https://www.kraken.com/help/api\n\n\nExamples\n--------\n\nA few package use examples are available in the examples_ directory.\n\n.. _examples: examples/\n\n\nInstallation\n\
    ------------\n\nThis package requires Python 3.3 or later. The module will be called\n``krakenex``.\n\nA `PyPI package`_ is available.\n\nFor general use, there is only one direct dependency: `requests`_.\n\
    \n.. _PyPI package: https://pypi.python.org/pypi/krakenex\n.. _requests: http://docs.python-requests.org/\n\n\nLocally for a project, in a virtual environment (recommended)\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\
    \nThis requires ``python-virtualenv`` and ``python-pip``.\n\nIn a terminal:\n\n.. code-block:: sh\n\n   # create directory for a project that'll be using krakenex\n   mkdir my-project\n   cd my-project\n\
    \   # bootstrap virtualenv\n   export VIRTUAL_ENV=.virtualenv/krakenex\n   mkdir -p $VIRTUAL_ENV\n   virtualenv $VIRTUAL_ENV\n   source $VIRTUAL_ENV/bin/activate\n   # install from PyPI\n   pip install\
    \ krakenex\n\nFor more information on ``virtualenv``, see `its documentation`_.\n\n.. _its documentation: https://virtualenv.pypa.io/en/stable/\n\nFor the user\n^^^^^^^^^^^^\n\nUsing ``pip``:\n\n..\
    \ code-block:: sh\n\n   # install from PyPI\n   pip install --user krakenex\n   # ... or from local git repo clone\n   cd CLONE-OF-GIT-REPO\n   pip install --user .\n\nSystem-wide (not recommended)\n\
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nIn general, use the distribution's package manager.\n\nIf it's unavailable, one can use ``pip``:\n\n.. code-block:: sh\n\n   # install from PyPI\n   pip install krakenex\n\
    \   # ... or from local git repo clone\n   cd CLONE-OF-GIT-REPO\n   pip install .\n\n   \nAttribution\n-----------\n\n\"Core\" code is licensed under LGPLv3. See ``LICENSE.txt`` and\n``LICENSE-GPLv3.txt``.\n\
    \nExamples are licensed under the Simplified BSD license. See\n``examples/LICENSE.txt``.\n\n`Payward's PHP API`_, Alan McIntyre's `BTC-e API`_,\nand ScriptProdigy's `Cryptsy Python API`_ were used as\n\
    examples when writing the original python2-krakenex_ package.\nIt was then ported to Python 3.\n\n.. _Payward's PHP API: https://github.com/payward/kraken-api-client\n.. _BTC-e API: https://github.com/alanmcintyre/btce-api\n\
    .. _Cryptsy Python API: https://github.com/ScriptProdigy/CryptsyPythonAPI\n.. _python2-krakenex: https://github.com/veox/python2-krakenex\n\n\nSoftware that uses ``krakenex``\n-------------------------------\n\
    \n* clikraken_ - command-line client for the Kraken exchange\n* CurrencyViewer_ - short program for crypto to fiat conversion and data extraction\n* Telegram-Kraken-Bot_ - Telegram bot to trade on Kraken\
    \ exchange\n\n.. _clikraken: https://github.com/zertrin/clikraken\n.. _CurrencyViewer: https://github.com/smechaab/krakenex-CurrencyViewer\n.. _Telegram-Kraken-Bot: https://github.com/Endogen/Telegram-Kraken-Bot\n\
    \n\nDevelopment notes\n-----------------\n\nDo not annoy the Kraken with tests\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nSome tests may be making queries to the Kraken API server.\n\nIf you intend to do\
    \ development on this package, and have tests enabled\non `Travis CI`_, be sure to limit concurrent jobs to 1, and enable all\npossible auto-cancellations.\n\n(Better yet, don't rely on public infrastructure,\
    \ but run the tests\nlocally first.)\n\n.. _Travis CI: https://travis-ci.org\n\nNo Python 2\n^^^^^^^^^^^\n\nThis package will never support Python 2. There will be no changes made\nto enable compatibility\
    \ with Python 2. Python 3.0 was `released in\n2008`_, before Bitcoin was.\n\nThere is no reason to support Python 2 except for compatibility with\nsystems from the pre-blockchain era.\n\nThe fact that\
    \ some GNU/Linux distributions still ship with Python 2 as\nthe default seems unfortunate to me. However, I will not support this\nmadness with my precious time.\n\nIf you have a valid reason to use\
    \ Python 2, see python2-krakenex_. Be\nwarned, though, that it is unmaintained.\n\n.. _released in 2008: https://en.wikipedia.org/wiki/History_of_Python#Version_3.0"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
